### ISSUE TITLE
IP web cams option possible?

### ISSUE THREAD

**Issue by vMeph** [pelrun/ugs-platform-plugin-camera#2]
First of all great plugin you have achived
Was wondering if would be possible to also insert ip web cams in options on what cams to chose from other then computer camera
Would this be dificult to implement?

Apart from this, great job
Thank you!!!!!

**Comment by pelrun** [comment]
It's possible, I'm just not sure when I can get around to implementing it.

**Comment by vMeph** [comment]
i have come across some java aplication that calls IP cam adresses, unfortunatly my java skills no good :(
on pass i did a post about the pendant that its on UGS its some aplication that gives you a IP so if you have a smartphone you insert that IP on it and you can acess the AP from smartphone then you can control machine from it and you can see what is doing etc..
unfortunatly that app as alot bugs, but the idea of having something like that AP on a smartphone that you can watch and control machine from distance can be very promissing
i leave in here a link to the post for you can take a look in end there is a link that shows how to use IP web cam, but that tutorial you got to put the IP that you want to use on the java code, so some adjustments would need to be made like a place to insert the IP and replace the one on the code
i wasnt able to eaven come close to make it but like i saied my java skills are 0 hehe

https://github.com/winder/Universal-G-Code-Sender/issues/672

if you got no IP camera to make tests to  you can use free aps from playstore for the android smart phone like the IP web cam that will turn the smartphone camera into a IP web cam

**Comment by pelrun** [comment]
The webcam library I'm using supports IP cameras already, it just needs a bunch of custom code and UI added.

**Comment by vMeph** [comment]
any advances on this?
